package org.softgreen.sistcoop.organizacion.ejb.models.jpa.entities;

// Generated 02-may-2014 11:48:28 by Hibernate Tools 4.0.0

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * TransaccionBovedaCaja generated by hbm2java
 */

@Table(name="TRANSACCION_BOVEDA_BOVEDA")
@XmlRootElement
@XmlAccessorType(XmlAccessType.NONE)
public class TransaccionBovedaBovedaEntity extends TransaccionInternaEntity implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private Long id;
	private HistorialBovedaEntity historialBovedaOrigen;
	private HistorialBovedaEntity historialBovedaDestino;

	private BigDecimal saldoDisponibleOrigen;
	private BigDecimal saldoDisponibleDestino;

	private boolean estadoSolicitud;
	private boolean estadoConfirmacion;

	private String origen;

	private Set detalle = new HashSet(0);

	public TransaccionBovedaBovedaEntity() {
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public HistorialBovedaEntity getHistorialBovedaOrigen() {
		return historialBovedaOrigen;
	}

	public void setHistorialBovedaOrigen(HistorialBovedaEntity historialBovedaOrigen) {
		this.historialBovedaOrigen = historialBovedaOrigen;
	}
	
	public HistorialBovedaEntity getHistorialBovedaDestino() {
		return historialBovedaDestino;
	}

	public void setHistorialBovedaDestino(HistorialBovedaEntity historialBovedaDestino) {
		this.historialBovedaDestino = historialBovedaDestino;
	}

	public BigDecimal getSaldoDisponibleOrigen() {
		return saldoDisponibleOrigen;
	}

	public void setSaldoDisponibleOrigen(BigDecimal saldoDisponibleOrigen) {
		this.saldoDisponibleOrigen = saldoDisponibleOrigen;
	}

	public BigDecimal getSaldoDisponibleDestino() {
		return saldoDisponibleDestino;
	}

	public void setSaldoDisponibleDestino(BigDecimal saldoDisponibleDestino) {
		this.saldoDisponibleDestino = saldoDisponibleDestino;
	}

	public boolean isEstadoSolicitud() {
		return estadoSolicitud;
	}

	public void setEstadoSolicitud(boolean estadoSolicitud) {
		this.estadoSolicitud = estadoSolicitud;
	}

	public boolean isEstadoConfirmacion() {
		return estadoConfirmacion;
	}

	public void setEstadoConfirmacion(boolean estadoConfirmacion) {
		this.estadoConfirmacion = estadoConfirmacion;
	}

	public String getOrigen() {
		return origen;
	}

	public void setOrigen(String origen) {
		this.origen = origen;
	}

	public Set getDetalle() {
		return detalle;
	}

	public void setDetalle(Set detalle) {
		this.detalle = detalle;
	}

}
